//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wyplata
    {
        public int IdWyplay { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<decimal> Kwota { get; set; }
    }
}
